## numpy

In [29]:
# Numerical arrays.
import numpy as np

### Resources

https://numpy.org/doc/stable/user/absolute_beginners.html

### Multidimensional Homogeneous Arrays

https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [30]:
# A 2D array of integers.
X = np.array([[1, 2, 3], [4, 5, 6]])

# Show.
print(X)

[[1 2 3]
 [4 5 6]]


In [31]:
# Number of dimensions.
print(X.ndim)

2


In [32]:
# Shape of the array.
print(X.shape)

(2, 3)


In [33]:
# Type of the elements.
print(X.dtype)

int64


### Operations

In [34]:
# Two arrays.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Show.
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [35]:
# Adding constants.
A + 5

array([[6, 7],
       [8, 9]])

In [36]:
# Adding two arrays.
A + B

array([[ 6,  8],
       [10, 12]])

In [37]:
# Multiplying by a constant.
A * 2

array([[2, 4],
       [6, 8]])

In [38]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [39]:
# Matrix multiplication.
A @ B

array([[19, 22],
       [43, 50]])

### Accessing Elements

In [40]:
# Recall A.
A

array([[1, 2],
       [3, 4]])

In [41]:
# Zeroth row, first column.
A[0, 1]

np.int64(2)

In [42]:
# First row.
A[0]

array([1, 2])

In [43]:
# First column.
A[:,1]

array([2, 4])

In [44]:
# An array with lots of elements.
X = np.arange(10, 21, 3)

# Show X.
print(X)

[10 13 16 19]


In [45]:
# An array with lots of elements.
X = np.arange(20)

# Show X.
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [46]:
# The first five elements.
X[0:5]

array([0, 1, 2, 3, 4])

In [47]:
# The first five elements.
X[:5]

array([0, 1, 2, 3, 4])

In [48]:
# The next five elements.
X[5:10]

array([5, 6, 7, 8, 9])

In [49]:
# The elements from index 5 up.
X[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
# Every second element.
X[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
# Every second element.
X[0:len(X):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### End